
version: "3.9"
services:
  reverse-proxy:
      image: traefik:v2.10.5
      container_name: traefik
      ports:
        - "80:80"
        - "443:443"
      command:
        - --api.dashboard=true
        - --providers.docker=true
        - --providers.docker.exposedbydefault=false
        - --entrypoints.web.address=:80
        - --entrypoints.websecure.address=:443
        - --certificatesresolvers.myresolver.acme.httpchallenge=true
        - --certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web
        - --certificatesresolvers.myresolver.acme.email=e-learning@glamorouscolors.nl
        - --certificatesresolvers.myresolver.acme.storage=acme.json
        # # global redirect to https
        - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./traefik/acme.json:/acme.json
      labels:
        # Dashboard
        - "traefik.enable=true"
        - "traefik.http.routers.dashboard.service=api@internal"
        - "traefik.http.routers.dashboard.rule=Host(`traefik.e-learning.glamorouscolors.nl`)"
        - "traefik.http.routers.dashboard.entrypoints=websecure"
        - "traefik.http.routers.dashboard.tls.certresolver=myresolver"
        - "traefik.http.routers.dashboard.middlewares=authtraefik"
        - "traefik.http.middlewares.authtraefik.basicauth.users=user:$2a$13$1cSrKi/NVaYz5mE8ekhmrOLBRsCoQtaN3Ai42hZPdbibScRJi631a" # https://www.transip.nl/htpasswd/
      restart: always

  e-learning:
    image: nginx:latest
    container_name: e-learning
    volumes:
      - ./nginx/html:/usr/share/nginx/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.e-learning-https.rule=Host(`e-learning.glamorouscolors.nl`)"
      - "traefik.http.routers.e-learning-https.entrypoints=websecure"
      - "traefik.http.routers.e-learning-https.tls.certresolver=myresolver"
    restart: always